export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';
export const ADD_EMPLOYEES = 'ADD_EMPLOYEES';
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
